// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-0b-T91qW5AWkZyr6wfDHQswOrGwFNNY',
    appId: '1:670300356353:web:f94de807456a4258fe2500',
    messagingSenderId: '670300356353',
    projectId: 'lumiere-a960e',
    authDomain: 'lumiere-a960e.firebaseapp.com',
    storageBucket: 'lumiere-a960e.firebasestorage.app',
    measurementId: 'G-BM80VD5D4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1wHwhYeIqYwxntGLki1-ZMFIdNc_8rS8',
    appId: '1:670300356353:android:cf4858a75c3dcca9fe2500',
    messagingSenderId: '670300356353',
    projectId: 'lumiere-a960e',
    storageBucket: 'lumiere-a960e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDde2u1P5js-q3LIVZIkOeseaGR-5PYD-U',
    appId: '1:670300356353:ios:3478f92d7e44c801fe2500',
    messagingSenderId: '670300356353',
    projectId: 'lumiere-a960e',
    storageBucket: 'lumiere-a960e.firebasestorage.app',
    iosBundleId: 'com.example.lumiere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDde2u1P5js-q3LIVZIkOeseaGR-5PYD-U',
    appId: '1:670300356353:ios:3478f92d7e44c801fe2500',
    messagingSenderId: '670300356353',
    projectId: 'lumiere-a960e',
    storageBucket: 'lumiere-a960e.firebasestorage.app',
    iosBundleId: 'com.example.lumiere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-0b-T91qW5AWkZyr6wfDHQswOrGwFNNY',
    appId: '1:670300356353:web:f1f048135a3b9790fe2500',
    messagingSenderId: '670300356353',
    projectId: 'lumiere-a960e',
    authDomain: 'lumiere-a960e.firebaseapp.com',
    storageBucket: 'lumiere-a960e.firebasestorage.app',
    measurementId: 'G-CM8R49GJ93',
  );
}
